language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - pandoc
      - texinfo
      - texlive
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-math-extra
      - qpdf

warnings_are_errors: false

services:
  - redis-server

env:
  global:
    - TEST_DOREDIS=TRUE
    - R_LIBS_USER=~/R/library

after_success:
  - Rscript -e 'library(doRedis); covr::codecov()'
