language: r
sudo: required
env:
  global:
    - TEST_DOREDIS=TRUE

services:
  - redis-server

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(doRedis); covr::codecov()'
